server:
  port: 8080
  threads:
    virtual:
      enabled: true
spring:
  application:
    name: performance-app
  datasource:
    url: jdbc:postgresql://localhost:5432/perfdb
    username: perfuser
    password: perfpass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: "*"